services:
  - docker

install:
  - go get github.com/optiopay/klar
  - export REPO="avhost/docker-jekyll"


script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d --name db arminc/clair-db:$(date -d "1 day ago" +%Y-%m-%d)
  - docker run -d -p 6060-6061:6060-6061 --link db:postgres --name clair arminc/clair-local-scan:v2.0.1    
  - docker build -t $REPO:clair .
  - docker images
  - docker push $REPO:clair  
  - CLAIR_ADDR=http://localhost CLAIR_OUTPUT=High CLAIR_THRESHOLD=10 klar $REPO:clair 

after_success:
  - docker build -t $REPO .
  - docker push $REPO
  

